w09/d03/student/band_io/config/routes.rb
Rails.application.routes.draw do

  root 'welcome#index'

  resources :venues do

  resources :events
end
  resources :bands

end

w09/d03/student/band_io/app/models/band.rb
class Band < ActiveRecord::Base

end

w09/d03/student/band_io/app/models/event.rb
class Event < ActiveRecord::Base

end

w09/d03/student/band_io/app/models/venue.rb
class Venue < ActiveRecord::Base

end

w09/d03/student/band_io/app/controllers/bands_controller.rb
class BandsController < ApplicationController

  def index
    @bands = Band.all
  end

  def show
    @band = Band.find params[:id]
  end

  def new
    @band = Band.new
  end

  def create
    band = Band.create band_params
    redirect_to band_path(band)
  end

  def band_params
    params.require(:band).permit(:name, :genre, :has_explicit_lyrics)
  end

end

w09/d03/student/band_io/app/controllers/events_controller.rb
class EventsController < ApplicationController

  def index
    @events = Event.all
  end

  def show
    @event = Event.find params[:id]
  end

  def new
    @event = Event.new
  end

  def create
    event = Event.create event_params
    redirect_to event_path(event)
  end

  def event_params
    params.require(:event).permit( :date, :alcohol_served, :band_id, :venue_id )
  end

end

w09/d03/student/band_io/app/controllers/venues_controller.rb
class VenuesController < ApplicationController

  def index
    @venues = Venue.all
  end

  def show
    @venue = Venue.find params[:id]
  end

  def new
    @venue = Venue.new
  end

  def create
    venue = Venue.create venue_params
    redirect_to venue_path(venue)
  end

  def venue_params
    params.require(:venue).permit(:name, :city, :state, :is_family_friendly )
  end
end

w09/d03/student/band_io/app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController

  def index

  end

end

w09/d03/student/band_io/app/helpers/bands_helper.rb
module BandsHelper
end

w09/d03/student/band_io/app/helpers/events_helper.rb
module EventsHelper
end

w09/d03/student/band_io/app/helpers/venues_helper.rb
module VenuesHelper
end

w09/d03/student/band_io/app/views/events/_event.html.erb
<div class="event">
  <h1>Date:<%= event.date %></h1>
  <p>Alcohol Served: <%= event.alcohol_served %></p>
  <p>Band ID: <%= event.band_id %></p>
  <p>Venue ID: <%= event.venue_id %></p>
  <%= link_to "Event", event_path(event) %>
</div>

w09/d03/student/band_io/app/views/events/index.html.erb
<%= button_to "Create a Event!", new_event_path, method: "get" %>

<div class="events collection">
  <%= render @events %>
</div>

w09/d03/student/band_io/app/views/events/new.html.erb
<h1>Create Event</h1>

<%= form_for(@event) do |f| %>

  <%= f.label :date, "Date" %>:
  <%= f.date_field :date %><br />

  <%= f.label :alcohol_served, "Alcohol Served?" %>:
  <%= f.text_field :alcohol_served %><br />

  <%= f.label :band_id, "Band ID" %>:
  <%= f.text_field :band_id %><br />

  <%= f.label :venue_id, "Venue ID" %>:
  <%= f.text_field :venue_id %><br />

  <%= f.submit %>

<% end %>

w09/d03/student/band_io/app/views/events/show.html.erb
<%= render "event", event: @event %>

 <%= link_to "Back to Events", events_path %>

w09/d03/student/band_io/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>BandIo</title>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
</head>
<body>
<h1><%= link_to "Band.io", root_path %></h1>
<%= yield %>

</body>
</html>

w09/d03/student/band_io/app/views/venues/_venue.html.erb
<div class="venue">
  <h1><%= venue.name %></h1>
  <h2>City: <%= venue.city %></h2>
  <p>State: <%= venue.state %></p>
  <p>Family Friendly: <%= venue.is_family_friendly %></p>
  <%= link_to "Go to Venue", venue_path(venue) %>
</div>

w09/d03/student/band_io/app/views/venues/index.html.erb
<%= button_to "Create a Venue!", new_venue_path, method: "get" %>

<div class="venues collection">
  <%= render @venues %>
</div>

w09/d03/student/band_io/app/views/venues/new.html.erb
<%= form_for @venue do |f| %>
  <%= f.label :name, "Name" %>:
  <%= f.text_field :name %><br />

  <%= f.label :city, "City" %>:
  <%= f.text_field :city %><br />

  <%= f.label :state, "State" %>:
  <%= f.text_field :state %><br />

  <%= f.label :is_family_friendly, "Family Friendly"%>:
  <%= f.text_field :is_family_friendly%>

  <%= f.submit %>


<% end %>

w09/d03/student/band_io/app/views/venues/show.html.erb
<%= render "venue", venue: @venue %>

 <%= link_to "Back to Venues", venues_path %>

<%= link_to "Create a new Event!", new_venue_event_path(@venue) %>